name: Run MLB Matchup Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Every 15 minutes
  workflow_dispatch: # Optional: lets you manually trigger from GitHub
  repository_dispatch:
    types: [scheduled-run]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Practice Lineup
        run: python MLB_Matchup/src/MLBMatchup.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage only specific folders
        run: |
          git add MLB_Matchup/images/
          git add MLB_Matchup/data/

      - name: Commit and push if changes exist
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update images and data folders"
            git push
          fi

permissions:
  contents: write
